#:import random random

<ScatterTextWidget>:
    orientation: 'vertical'
    TextInput: 
        id: default_textinput
        font_size: 130
        size_hint_y: None
        height: 200
        text: 'default'
        on_text: my_label.color = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]
    FloatLayout:
        Scatter:
            Label:
                id: my_label
                text: default_textinput.text
                font_size: 130




    